### ISSUE TITLE
Store composition seems to clobber original store value

### ISSUE THREAD

**Issue by marbemac** [Omnistac/zedux#130]
### Description

New to Zedux so this could be user error, but calling `store.use` seems to clobber the initial state originally set on the store.

Example: https://github.com/marbemac/zedux-use-bug/blob/main/src/App.tsx

When the component is rendered:

<img width="556" alt="Screenshot 2024-11-23 at 4 02 57 PM" src="https://github.com/user-attachments/assets/eab0e408-c39d-4b52-9a6b-59a8cc6de6bf">

### Reproduction

Repro: https://github.com/marbemac/zedux-use-bug

**Comment by bowheart** [comment]
@marbemac This is expected, but you've made me realize: The new store docs have no mention of this 😬 . The old docs had this (clearly important) line:

```ts
:::important
Each store should only use one core pattern - either the Zero Config or Reducer pattern. A store can contain other stores that use different patterns, but it shouldn't use both patterns itself.
:::
```

(can see when it was added 4 years ago [here](https://github.com/Omnistac/zedux/commit/061c83aee0ed8bb06f3e6d76172b14e33e067f40#diff-3a0141e5acfc1185643d9ae4c8994e9fe2f3cd41bcd1f6e05874322e74533dd9R41), I haven't tracked down where we took it out yet).

I will make sure to get that in the new doc somewhere prominent. The gist is: Stores can be either zero-config or controlled, not both. Composed stores are "controlled" by their child stores/reducers.

Here's an example of what your code could look like, addressing your TS note too:

```ts
const childAtom = atom('child', ({ groupId }: { groupId: string }) => {
  const parent = injectAtomInstance(parentAtom, [{ groupId }]);

  const ownStore = injectStore<{ childId: string; parentValue?: string }>({
    childId: 'some-id',
  });

  const composedStore = injectStore(() =>
    createStore({ ownValue: ownStore, parentValue: parent.store })
  );

  composedStore.use({ ownValue: ownStore, parentValue: parent.store });

  return composedStore;
});
```

Let me know if that makes sense, sorry about the doc mixup.

**Comment by marbemac** [comment]
Ah yeah ok I see, thanks! Definitely feels a bit unintuitive / awkward, but I noticed in the signals RFC that you're looking to solve this with `injectMappedSignal` which does indeed look much more intuitive.

**Comment by marbemac** [comment]
Wait actually doesn't this mean that the returned store:

1. Now has childId nested under ownValue e.g. `store.ownValue.childId`. Not the end of the world of course, can adjust to nest "own store" properties under their own key in the returned store.
2. Has both `store.ownValue.parentValue` and `store.parentValue` - does it matter which is used?

**Comment by bowheart** [comment]
Signals will improve this a lot, removing the redundant `.use` call and the verbose `injectStore(() => createStore())`. With stores though, btw, you can prevent extra nesting by creating stores for individual keys. For example:

```ts
const childAtom = atom('child', ({ groupId }: { groupId: string }) => {
  const parent = injectAtomInstance(parentAtom, [{ groupId }]);

  const childIdStore = injectStore('some-id');

  const composedStore = injectStore(() =>
    createStore({ childId: childIdStore, parentValue: parent.store })
  );

  composedStore.use({ childId: childIdStore, parentValue: parent.store });

  return composedStore;
});
```

**Comment by marbemac** [comment]
Thanks! All works, will close this out. Looking forward to the signals work :).
