### ISSUE TITLE
Docs: "Edit this page" button points to incorrect location.

### ISSUE THREAD

**Issue by benlesh** [Omnistac/zedux#24]
In the documentation, the `Edit this page` link points to the incorrect place.

![image](https://user-images.githubusercontent.com/1540597/233408573-6c2f767f-9a10-4041-8eed-153672f9fae1.png)

For example:

Currently it links to: https://github.com/Omnistac/zedux/tree/master/docs/about/introduction.mdx

I recommend it is linked to: https://github.com/Omnistac/zedux/edit/master/docs/docs/about/introduction.mdx

**Comment by bowheart** [comment]
good find! Thanks for pointing out. Yep, looks like our `editUrl` in docusaurus config is wrong. And the `edit` url is a great addition. Fix incoming
